// import prisma from "./prisma";

// async function main() {
//   const products = [
//     {
//       name: "Violet Mist",
//       brand: "Misk",
//       category: "Eau de Parfum",
//       price: 120,
//       imageUrl: "/assets/perfume-violet.jpg",
//       description:
//         "An enchanting blend of rare violet and soft vanilla, capturing the essence of a twilight garden.",
//       notesTop: "Bergamot",
//       notesHeart: "Black Orchid",
//       notesBase: "Patchouli",
//       volume: ["50ml", "100ml"],
//       stock: "inStock",
//       badge: "bestSeller",
//       family: "Floral",
//     },
//     {
//       name: "Amber Gold",
//       brand: "Misk",
//       category: "Eau de Toilette",
//       price: 145,
//       imageUrl: "/assets/perfume-amber.jpg",
//       description: "A warm and spicy fragrance with notes of amber, honey, and golden vanilla.",
//       notesTop: "Pink Pepper",
//       notesHeart: "Jasmine",
//       notesBase: "Amber",
//       volume: ["50ml", "100ml"],
//       stock: "inStock",
//       family: "Oriental",
//     },
//     {
//       name: "Pure Air",
//       brand: "Misk",
//       category: "Eau de Cologne",
//       price: 95,
//       imageUrl: "/assets/perfume-aqua.jpg",
//       description: "A crisp and refreshing scent inspired by ocean breezes and clear skies.",
//       notesTop: "Sea Salt",
//       notesHeart: "Lily",
//       notesBase: "White Musk",
//       volume: ["50ml", "100ml"],
//       stock: "lowStock",
//       badge: "new",
//       family: "Fresh",
//     },
//     {
//       name: "Noir Nuit",
//       brand: "Misk",
//       category: "Parfum Intense",
//       price: 195,
//       imageUrl: "/assets/perfume-noir.jpg",
//       description: "A mysterious and seductive fragrance for those who embrace the night.",
//       notesTop: "Black Pepper",
//       notesHeart: "Dark Rose",
//       notesBase: "Oud",
//       volume: ["50ml", "100ml"],
//       stock: "inStock",
//       family: "Woody",
//     },
//     {
//       name: "Rose Petal",
//       brand: "Misk",
//       category: "Eau de Parfum",
//       price: 135,
//       imageUrl: "/assets/perfume-rose.jpg",
//       description: "A romantic bouquet of Bulgarian roses with hints of soft peony and musk.",
//       notesTop: "Rose",
//       notesHeart: "Peony",
//       notesBase: "Musk",
//       volume: ["30ml", "50ml", "100ml"],
//       stock: "inStock",
//       family: "Floral",
//     },
//     {
//       name: "Emerald Forest",
//       brand: "Misk",
//       category: "Eau de Parfum",
//       price: 160,
//       imageUrl: "/assets/perfume-emerald.jpg",
//       description: "A fresh and botanical journey through a lush green forest after rain.",
//       notesTop: "Green Tea",
//       notesHeart: "Moss",
//       notesBase: "Cedarwood",
//       volume: ["50ml", "100ml"],
//       stock: "inStock",
//       badge: "new",
//       family: "Fresh",
//     },
//     {
//       name: "Oriental Spice",
//       brand: "Misk",
//       category: "Parfum Intense",
//       price: 210,
//       imageUrl: "/assets/perfume-oriental.jpg",
//       description: "An opulent blend of exotic spices, saffron, and rich amber.",
//       notesTop: "Saffron",
//       notesHeart: "Cinnamon",
//       notesBase: "Sandalwood",
//       volume: ["50ml", "100ml"],
//       stock: "lowStock",
//       badge: "limited",
//       family: "Oriental",
//     },
//     {
//       name: "Midnight Orchid",
//       brand: "Misk",
//       category: "Eau de Parfum",
//       price: 185,
//       imageUrl: "/assets/perfume-violet.jpg",
//       description: "An intoxicating blend of rare orchid and dark vanilla, designed for those who embrace the night.",
//       notesTop: "Bergamot",
//       notesHeart: "Black Orchid",
//       notesBase: "Patchouli",
//       volume: ["50ml", "100ml"],
//       stock: "inStock",
//       badge: "bestSeller",
//       family: "Floral",
//     },
//   ];

//   for (const product of products) {
//     await prisma.product.create({ data: product });
//   }

//   console.log("🌱 All products seeded successfully!");
// }

// main()
//   .catch((e) => console.error(e))
//   .finally(() => prisma.$disconnect());
